name: Android APK (Debug)

on:
  push: { branches: [ main ] }
  pull_request: { branches: [ main ] }
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      ANDROID_SDK_ROOT: /usr/local/lib/android/sdk
      ANDROID_HOME: /usr/local/lib/android/sdk
      JAVA_TOOL_OPTIONS: -Xmx3g

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      # (Opcional) Ver qué SDK/Build-tools ya están en el runner
      - name: Show installed Android SDK packages
        run: |
          "${ANDROID_SDK_ROOT}/cmdline-tools/latest/bin/sdkmanager" --list || true
          ls -R "${ANDROID_SDK_ROOT}/build-tools" || true
          ls -R "${ANDROID_SDK_ROOT}/platforms" || true

      - name: Build (Debug)
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 8.7
          arguments: |
            --no-daemon
            --stacktrace
            --info
            --warning-mode=all
            -Pkotlin.compiler.execution.strategy=in-process
            clean
            assembleDebug

      - name: List APKs
        run: ls -R app/build/outputs/apk || true

      - name: Upload debug APK
        uses: actions/upload-artifact@v4
        with:
          name: app-debug-apk
          path: app/build/outputs/apk/debug/*.apk
          if-no-files-found: error
